# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogIn(object):
    def setupUi(self, LogIn):
        LogIn.setObjectName("LogIn")
        LogIn.resize(1200, 680)
        self.centralwidget = QtWidgets.QWidget(LogIn)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{background:rgb(255, 255, 255)}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_cap = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label_cap.sizePolicy().hasHeightForWidth())
        self.label_cap.setSizePolicy(sizePolicy)
        self.label_cap.setMinimumSize(QtCore.QSize(640, 480))
        self.label_cap.setText("")
        self.label_cap.setObjectName("label_cap")
        self.horizontalLayout.addWidget(self.label_cap)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 120))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_ok = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_ok.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        self.pushButton_delete = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_2.addWidget(self.pushButton_delete)
        self.verticalLayout.addWidget(self.widget_2)
        # self.label_picture = QtWidgets.QLabel(self.widget)
        # self.label_picture.setMinimumSize(QtCore.QSize(540, 360))
        font = QtGui.QFont()
        font.setPointSize(13)
        # self.label_picture.setFont(font)
        # self.label_picture.setStyleSheet("border-image:url(:/decorate/zzf.jpg)")
        # self.label_picture.setText("")
        # self.label_picture.setObjectName("label_picture")
        # self.verticalLayout.addWidget(self.label_picture)
        self.horizontalLayout.addWidget(self.widget)
        LogIn.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LogIn)
        self.statusbar.setObjectName("statusbar")
        LogIn.setStatusBar(self.statusbar)

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)

    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "AirWriting"))
        self.label_2.setText(_translate("LogIn", "输入框"))
        self.pushButton_ok.setText(_translate("LogIn", "确定"))
        self.pushButton_delete.setText(_translate("LogIn", "删除"))

